import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 130,
    paddingVertical: 60,
    paddingHorizontal: 20,
  },
  content: {
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 30,
    paddingVertical: 50,
    paddingHorizontal: 50,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 20,
    elevation: 10,
    width: "100%",
    maxWidth: 300,
  },
  heading: {
    fontFamily: "Outfit_700Bold",
    fontSize: 27,
    color: "#111827",
    textAlign: "center",
    marginBottom: 10,
  },
  prompt: {
    width: 250,
    fontFamily: "Outfit_500Medium",
    fontSize: 16,
    color: "#374151",
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 20,
    paddingHorizontal: 16,
  },
  input: {
    width: 230,
    backgroundColor: "#F3F4F6",
    borderRadius: 30,
    paddingVertical: 7,
    paddingHorizontal: 15,
    fontSize: 16,
    fontFamily: "Outfit_500Medium",
    color: "#111827",
    textAlign: "center",
    borderWidth: 1,
    borderColor: "#D1D5DB",
  },
  primaryBtn: {
    backgroundColor: "#4F46E5",
    paddingVertical: 10,
    borderRadius: 30,
    width: 230,
    alignItems: "center",
    shadowColor: "#4F46E5",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 8,
  },
  primaryBtnText: {
    fontFamily: "Outfit_700Bold",
    color: "#FFF",
    fontSize: 18,
    letterSpacing: 0.5,
  },
  scrollContent: {
    alignItems: "center",
    paddingBottom: 60,
    width: "100%",
  },
  pickerWrapper: {
    width: 230,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    overflow: "hidden",
    marginTop: 12,
    borderWidth: 1,
    borderColor: "transparent",
  },
  picker: {
    width: 230,
    backgroundColor: "#F5F5F5",
    borderRadius: 20,
    fontSize: 16,
    fontFamily: "Outfit_500Medium",
  },
  progressBarContainer: {
    height: 8,
    width: "100%",
    backgroundColor: "#E5E7EB",
    borderRadius: 20,
    marginBottom: 20,
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#4F46E5",
    borderRadius: 20,
  },
  passwordCriteria: {
    fontFamily: "Outfit_500Medium",
    fontSize: 16,
    color: "#374151",
    textAlign: "left",
    marginBottom: 8,
    width: '100%',
  },
  passwordCriteriaItem: {
    fontFamily: "Outfit_500Medium",
    fontSize: 14,
    color: "#6B7280",
    marginLeft: 10,
    lineHeight: 22,
  },
  errorText: {
    color: "red",
    fontSize: 12,
    marginTop: 4,
    textAlign: "center",
  },
});
